name: chain-docs

on:
  push:
    branches: [ master ]
    paths:
    - 'test'
    - 'docs/**'
    - 'ci/**'
    - '!README.md'
  issue_comment:
    types: [created, edited]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event.comment.body == '/RUN' && (github.actor == 'allthatjazzleo' || github.actor == 'tomtau' || github.actor == 'lezzokafka' || github.actor == 'yihuang' || github.actor == 'calvinlauco' || github.actor == 'foreseaz' || github.actor == 'CeruleanAtMonaco' || github.actor == 'devashishdxt' || github.actor == 'leejw51crypto'))
    steps:
    - name: Github API Request
      id: request
      uses: octokit/request-action@v2.0.0
      if: github.event_name == 'issue_comment'
      with:
        route: ${{ github.event.issue.pull_request.url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get PR informations
      id: pr_data
      if: github.event_name == 'issue_comment'
      run: |
        echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
        echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).base.repo.full_name }}"
    - name: Checkout PR Branch
      uses: actions/checkout@v2
      if: github.event_name == 'issue_comment'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ steps.pr_data.outputs.repo_name }}
        ref: ${{ steps.pr_data.outputs.branch }}
    - name: Check MASTER code
      uses: actions/checkout@v2
      if: github.event_name == 'push'
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: ci
      env:
        EVENT: ${{ github.event_name }}
      run: |
        echo this event is triggered by $EVENT
        echo -e "\ncat test"
        cat test